#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from grc.companion.main import MainController

"""
Companion should handle the main launch of everything.
Initialize the platform and model, then launch the GUI.
"""

if __name__ == "__main__":
    import sys

    # Initialize the flowgraph model

    # Setup the main qt application and window
    app = QtWidgets.QApplication(sys.argv)

    # Initialize the GUI
    main = MainController()
    main.show()
    
    # Launch the qt app
    sys.exit(app.exec_())

